baseURL: "https://ekxs0109.github.io/"
languageCode: "zh-CN"
title: "ekxs'Blog"
theme: 'PaperMod'
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
Copyright: "[èœ€ICPå¤‡19028772å·](https://beian.miit.gov.cn/) | "

#é…ç½®èœå•
menu:
  main:
    - name:  æœç´¢
      url: search/
      weight: 2
    - name: å½’æ¡£
      url: archives/
      weight: 4
    - name: åˆ†ç±»
      url: tags/
      weight: 3
    - name: é¦–é¡µ
      url: /
      weight: 1
    # - name: å…³äºæˆ‘
    #   url: about/
    #   weight: 10

params:
  defaultTheme: auto
  comments: true
  homeInfoParams:
        Title: "ä½ å¥½ï¼Œäººç±» ğŸ¤–" # optional default will be site title
        Content: "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ï¼Œå–œæ¬¢æŠ˜è…¾å„ç§æŠ€æœ¯å’Œäº‹ç‰©ã€‚\n\nåœ¨è¿™é‡Œï¼Œæˆ‘å°†åˆ†äº«æˆ‘çš„ç»éªŒå’Œè§è§£ï¼Œä¸å¤§å®¶ä¸€èµ·åŠªåŠ›æˆé•¿ã€‚"
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/ekxs0109/"
    - name: "leetcode"
      url: "https://leetcode.cn/u/ekxs/"
    - name: "rss"
      url: "/index.xml"
    - name: "email"
      url: "mailto:ekxs@outlook.com"

outputs:
    home:
        - HTML
        - RSS